import FoliationsGeneratedDynamicalSystemsCanonicalLaneLean.Basic
import FoliationsGeneratedDynamicalSystemsCanonicalLaneLean.FoliatedManifold
import FoliationsGeneratedDynamicalSystemsCanonicalLaneLean.HardyWeinbergEquilibrium
import FoliationsGeneratedDynamicalSystemsCanonicalLaneLean.LinkageAnalysis
import FoliationsGeneratedDynamicalSystemsCanonicalLaneLean.SequenceAlignment
import FoliationsGeneratedDynamicalSystemsCanonicalLaneLean.Phylogenetics
import FoliationsGeneratedDynamicalSystemsCanonicalLaneLean.FinalTheorem

namespace HautevilleHouse
namespace FoliationsGeneratedDynamicalSystemsCanonicalLaneLean

-- Aggregate module for the Foliations Generated Dynamical Systems canonical lane package.

end FoliationsGeneratedDynamicalSystemsCanonicalLaneLean
end HautevilleHouse